services:
  web:
    image: 08edgarallan94/service-order-system-sosv6:latest 
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 256M
    container_name: php_sosv6_app
    ports:
    # puedes definir los puertos maquina_anfitrion:contenedor que creas conveniente, solo hay que tener en cuenta los permisos de conexión del puerto de la maquina anfitrión o si el puerto está siendo utilizado por otra instancia.
      - "8081:80" 
    environment:
      - SQL_SERVER=mssql_server
      - SQL_DATABASE=SOSv6DB
      - SQL_USER=sa
      - SQL_PASSWORD=PasswordSeguro123!
    # en localhost solo se podrá ver la aplicación web en la maquina donde se ejecute el docker compose, si se quiere ver en otros dispositivos a parte de la maquina anfitrion hay que sustituir el localhost de esta variable de entorno por tu IPv4 conectado a tu red local, hacer esto es completamente opcional.
      - SOSV6_URL=http://localhost:8081/SOSv6/service-order-system/ 
    networks:
      - sosv6-network 
    depends_on:
      - db 
    volumes:
      - web_data:/var/www/html
  jest:
    image: 08edgarallan94/service-order-system-sosv6-jest-tests:latest
    container_name: jest_tests
    networks:
      - sosv6-network     
  db:
    build:
      context: .
      dockerfile: Dockerfile.sql
    container_name: mssql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=PasswordSeguro123!
    ports:
    # puedes cambiar los puertos maquina_anfitrion:contenedor por los que creas conveniente, solo hay que tener en cuenta los permisos de conexión del puerto de la maquina anfitrión o si el puerto está siendo utilizado por otra instancia.
      - "1434:1433"
    networks:
      - sosv6-network 
    volumes:
      - sql_data:/var/opt/mssql/sql_data
      - ./backup:/var/opt/mssql/backup

networks:
  sosv6-network:
    driver: bridge 

volumes:
  sql_data:
  web_data:
